name: Build Release APK

on:
  workflow_dispatch:   # Запуск только вручную

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      P4A_RELEASE_KEYSTORE: ${{ github.workspace }}/sensitivityconverter.keystore
      P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.KEYSTORE_PASSWORD }}
      P4A_RELEASE_KEYALIAS: ${{ secrets.KEY_ALIAS }}
      P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > sensitivityconverter.keystore

      - name: Build Release APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android release
          buildozer_version: stable

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: sensitivityconverter-release-apk
          path: bin/*.apk
